/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car({ color, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cargood.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.82, 0.82, 0.82]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.car.geometry}
          material={materials.CarColor}
        >
<meshStandardMaterial
          color={color}
          aoMap={materials.CarColor.aoMap}
          normalMap={materials.CarColor.normalMap}
          roughnessMap={materials.CarColor.roughnessMap}
          metalnessMap={materials.CarColor.metalnessMap}
          envMapIntensity={0.8}
        />
        </mesh>
                
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.car_1.geometry}
          material={materials.CarWindow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.car_2.geometry}
          material={materials.CarMetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.car_3.geometry}
          material={materials.CarTire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.car_4.geometry}
          material={materials.CarHeadlights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.car_5.geometry}
          material={materials.CarTaillights}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/cargood.glb')
